### ISSUE TITLE
Apply to be removed from the Bluecoat/K9 blocklist

### ISSUE THREAD

**Issue by voltagex** [nolanlawson/pokedex.org#12]
Content Blocked (content_filter_denied) 
 	Content Category: "Suspicious"

https://sitereview.bluecoat.com/sitereview.jsp

**Comment by voltagex** [comment]
I mean, corporate users probably aren't your target market but home users using the K9 filter will be affected too.

**Comment by nolanlawson** [comment]
Sorry, what is the fix for this? What part of the app is suspicious?

**Comment by voltagex** [comment]
Apologies - what I meant was that your site is on the Bluecoat filter list, probably because it's "new" to them, not because of any particular content. 

It looks like it was updated and is now categorised correctly: "This page is currently categorized as For Kids and Games   Last Time Rated/Reviewed: November 26, 2015 06:36:27 GMT  
This page has a risk level of Medium"
