### ISSUE TITLE
stopwatch.js should use console.time()/timeEnd()

### ISSUE THREAD

**Issue by paulirish** [nolanlawson/pokedex.org#13]
if so, you'd get these segments marked up in the Timeline profile. 

![image](https://cloud.githubusercontent.com/assets/39191/11406250/3d703604-9361-11e5-9bfb-8e28e2e93c8b.png)

**Comment by paulirish** [comment]
(this app is amazing btw. nice work, man)

**Comment by nolanlawson** [comment]
Thanks a lot @paulirish! And also thanks for your perf audits of various sites (including Squarespace, heh); I've learned a lot from them!

Fixed by 4c5be4e5c71ef685c4e6fdf43bcd102326c224fe
