### ISSUE TITLE
Image lazy loading doesn't fire on sidebar toggle

### ISSUE THREAD

**Issue by connorjburton** [nolanlawson/pokedex.org#18]
If you scroll down the page about half way with the menu open, then close the menu the images that get brought up (because of less rows) don't have their images loaded.

I guess the lazy load needs to fire on sidebar close success.

![pokedex lazy load](https://cloud.githubusercontent.com/assets/10538031/11424328/01a0de92-9444-11e5-98af-e3f8dbd63667.png)

**Comment by nolanlawson** [comment]
Ah, good catch! Yeah, if you look at `scrollingList.js` -> `onScroll()`, you'll see it fires an event to refresh the visible Pokémon sprites. We need to do that anytime the window changes size or when the menu is closed as well.

**Comment by nolanlawson** [comment]
fixed by https://github.com/nolanlawson/pokedex.org/pull/24
