### ISSUE TITLE
Pokémon sprite gets stuck sometimes

### ISSUE THREAD

**Issue by nolanlawson** [nolanlawson/pokedex.org#19]
The sprite façade occasionally seems to get stuck, based on reports from users: https://twitter.com/seriemajp/status/669955302230499329

**Comment by seriema** [comment]
I'm able to semi-consistently get this to happen. I'm using iOS 9 and both Chrome and Safari has this issue.

1. The "Pokémon profile page" seems to have its own scroll or something. It doesn't continue to scroll after a flick like the default behavior on phones. The main page does this though.
1. The first time I went into a Pokémon profile with Chrome, and then Safari, the image would get stuck like that.
1. Turning on flight mode seems to cause various issues, sometimes. On a profile, turn it off, go back to main page, pick the same Pokémon, would often make the scrolling even weirder. It could lock up completely so I can't scroll, or just scroll the bottom part, or the Pokémon profile pic would scroll away.

Here are some situations. Sorry the screenshots are so big. Can't seem to change them.

iOS, Chrome, bottom part scrolls but not the rest.
![2015-11-29 11 11 03](https://cloud.githubusercontent.com/assets/693684/11456497/87737f5e-968b-11e5-864d-e1c7fdb834fb.png)

iOS, Chrome, going offline and checking Pikachu again makes him move when scrolling.
![2015-11-29 11 12 08](https://cloud.githubusercontent.com/assets/693684/11456498/87739af2-968b-11e5-9e27-cf5330ec02bd.png)

iOS, Chrome, going back online and checking Pikachu again still has the scroll issue. Not fully reproducable though.
![2015-11-29 11 12 35](https://cloud.githubusercontent.com/assets/693684/11456500/877619d0-968b-11e5-9b89-051c875dd47e.png)

iOS, Safari, first time visit and checking Pikachu has the scroll issue.
![2015-11-29 11 16 03](https://cloud.githubusercontent.com/assets/693684/11456496/877376e4-968b-11e5-8b4f-7846a05ae1a6.png)

**Comment by nolanlawson** [comment]
Weird, airplane mode shouldn't change anything, unless the database failed to sync (in which case nothing will show up, or maybe partial data will show up). So far I'm unable to reproduce.

**Comment by seriema** [comment]
I haven't checked your code, but I had a feeling a large part of this "demo" was offline support? So yeah, I'd think something's off in the sync or offline-detection. But my first bet would be the "weird" custom scroll behaviour. Especially since when loading the page the Pokémon avatar is in the right position before the content gets there, so I guess it's position:absolute or something? That could account for the stuff moving around without necessarily following the page.

**Comment by nolanlawson** [comment]
If the site is offline, then it fetches exactly the same data from IndexedDB rather than a remote server. No "offline detection."

My guess is that sync failed, you went offline so had neither IndexedDB nor the remote server, so the worker threw an error and never returned. Will try to repro again.

**Comment by seriema** [comment]
Went to the site on a friends computer who's never seen it before. Had full wifi access with no issues before or after. Still got the same scroll issue with the site.

**Comment by nolanlawson** [comment]
I managed to reproduce once on desktop Chrome, but it only seems to happen during initial sync. I don't understand why.

**Comment by rgbkrk** [comment]
Interesting, I faced this issue only on initial sync for both Chrome and Safari. Goes away after reload.

**Comment by nolanlawson** [comment]
Might be a memory issue then. I think the initial sync might be hogging too many resources.
