### ISSUE TITLE
Discussion: Cache width/height requests

### ISSUE THREAD

**Issue by connorjburton** [nolanlawson/pokedex.org#21]
Correct me if I am wrong on any of the below.

For example, ```scrollingList.js -> binarySearchForFirstInvisibleChild() ``` will request the ```window.innerHeight``` every call. Even though the ```scroll``` event is denounced, this still causes un-necessary re-flows. We should only request ```window.innerHeight``` if the denounced ```resize``` event has finished.

We should also obviously share this cache with all other functions that require ```window.innerHeight``` or any other properties/functions that cause re-flows.

I'm happy to take a crack at this.

**Comment by connorjburton** [comment]
I guess PouchDB would be ideal for this.

**Comment by nolanlawson** [comment]
Hm, my understanding is that re-flows are going to be caused anyway by `getBoundingClientRect()`. I also tried hard-coding the `window.innerHeight`, and I'm not seeing any difference in the timeline or when I tick "Enable paint flashing"  (it still flashes on the debounce either way).

But @paullewis would know better than me! I'd be curious to know if it makes a difference. (For the record, [here's the function](https://github.com/nolanlawson/pokedex.org/blob/93696e1a97a14be0d6e9724bcd0dd9923b82a75f/src/js/client/main/scrollingList.js#L62-L72) we're talking about.)

**Comment by connorjburton** [comment]
Hm yes, I completely missed that ```getBoundingClientRect()``` - it's possible there is no improvement by changing it.

**Comment by paullewis** [comment]
For FLIP the first `getBoundingClientRec()` call should be done before any style mutations so we can reuse the previous frame's layout values. Then we apply the style change to move everything to the Last position (invalidating layout). Then we call `getBoundingClientRect()` again, which will trigger layout. 

So there's typically no benefit to caching values if FLIP is done correctly. The balancing act is in the forced styles & layout work, and whether that's cheap enough to do inside of 100ms, and thereby retain the impression of immediacy to the user.

**Comment by connorjburton** [comment]
Thanks for that @paullewis :) will close this
