### ISSUE TITLE
Search should be more visible

### ISSUE THREAD

**Issue by connorjburton** [nolanlawson/pokedex.org#25]
I didn't see the search bar for probably the first 10 times on the site, I think it should be in the purple heading at the top.

Don't know if this has happened to anyone else or my brightness/contrast is way too high.

**Comment by nolanlawson** [comment]
You are the second person to mention this; I think the contrast definitely needs to be turned up.

**Comment by nolanlawson** [comment]
fixed by 61b115666d234bf60ad39df7fd32cb5869a03e2c
