### ISSUE TITLE
Add -webkit-overflow-scrolling: touch to fix momentum scrolling on iOS

### ISSUE THREAD

**Issue by nolanlawson** [nolanlawson/pokedex.org#4]
Per https://twitter.com/HenrikJoreteg/status/669034858358771712 and https://css-tricks.com/snippets/css/momentum-scrolling-on-ios-overflow-elements/

**Comment by nolanlawson** [comment]
Hm, weird, I can fix scrolling inside the "detail view" by adding that property to `.detail-panel`, but I can't seem to fix the main list scrolling no matter what I do. :/

**Comment by nolanlawson** [comment]
Anybody who wants to take a look; that commit ^ fixes the detail panel, but not the main list somehow. Maybe related to the fact that I'm using `display: flex-items`?

**Comment by jthoms1** [comment]
The main list scrolls correctly (with momentum) for me on iOS 9.1. I will take a look to verify this fixes the detail page.

**Comment by nolanlawson** [comment]
The main list did not scroll properly for me on iOS... that's weird.

**Comment by lorensr** [comment]
For me the main list is working but the detail panel is not :)

**Comment by nolanlawson** [comment]
fixed by #58
