### ISSUE TITLE
autoprefixer is not prefixing your CSS rules even when set to..

### ISSUE THREAD

**Issue by samccone** [nolanlawson/pokedex.org#46]
Given this patch -- I was expecting to see all your `transform` rules with the -webkit prefix.. however someone is letting us down here.

![image](https://cloud.githubusercontent.com/assets/883126/16292440/43854de4-38c6-11e6-842f-bed8dfde028f.png)

To get UC browser going we will need to add prefixing in.

**Comment by nolanlawson** [comment]
Hm, did you check the `npm run serve` mode or the `npm run build` mode? postcss ought to do its thing in that case...

**Comment by samccone** [comment]
I was rolling right with `npm run build` -- let me know if there was anything else I should have been doing :)

I can continue my investigation if you are not sure just figured I would ask before I sunk any more time into things.

**Comment by nolanlawson** [comment]
Hm no, I actually assumed PostCSS was already doing its thing. Your code looks right to me; no idea why prefixes aren’t being applied. :confused:

**Comment by nolanlawson** [comment]
Oh wait, I see what's going on. `mainCss` is not being autoprefixed like all the other CSS files. I'll fix.

**Comment by samccone** [comment]
:goat: :dancer:
