### ISSUE TITLE
Interesting error stack in UC browser when going into detail view

### ISSUE THREAD

**Issue by samccone** [nolanlawson/pokedex.org#47]
![image](https://cloud.githubusercontent.com/assets/883126/16327742/9b82578c-3987-11e6-9006-6f09ca334f8a.png)

**Comment by nolanlawson** [comment]
Hm, maybe RegeneratorRuntime doesn't support UC Browser? Cost of using ES6/ES7... 😛

**Comment by nolanlawson** [comment]
Although I am using an older version; maybe it's time to upgrade.

**Comment by samccone** [comment]
I searched the repo for issues... did not see anything like this so I am guessing it is something else

**Comment by samccone** [comment]
resolved :)
