### ISSUE TITLE
Store images using Cache API 

### ISSUE THREAD

**Issue by basiclaser** [nolanlawson/pokedex.org#50]
Hi, 
Did you consider using the Cache API to enable streaming and avoid blob conversion required to deliver images from IndexedDB?
reference: https://classroom.udacity.com/courses/ud899/lessons/6381510082/concepts/63774101800923

**Comment by nolanlawson** [comment]
I don't store any images in IndexedDB. The only images are Pokémon sprites, which are stores in CSS as base64, and those files are stored in the Cache API.
