### ISSUE TITLE
monsters-search-bar is missing a label

### ISSUE THREAD

**Issue by awayken** [nolanlawson/pokedex.org#63]
Accessibility recommendation from: https://dequeuniversity.com/rules/axe/1.1/label

I think [the MUI floating labels](https://www.muicss.com/docs/v1/css-js/forms) would best complement the existing design. I'll work on submitting a pull request.

**Comment by nolanlawson** [comment]
Thank you, I didn't realize that using placeholder as a replacement for label would hurt accessibility. Appreciate the PR!
