### ISSUE TITLE
iOS can scroll main list while detail view is visible

### ISSUE THREAD

**Issue by nolanlawson** [nolanlawson/pokedex.org#7]
Reported on Twitter: https://twitter.com/djbriane/status/669232271505817600?s=09

**Comment by codeshrew** [comment]
I encountered this on desktop Safari as well.

Safari Version 9.0.2 (11601.3.9)
Mac OS X El Capitan Version 10.11.2

Easiest way to reproduce is by placing your mouse on the background (outside the `div.detail-panel-content`) and scrolling.

**Comment by nickcolley** [comment]
One way to solve this is to unmount the main list, if you're doing a VDOM approach might be easy to do. If it's not there, it can't be scrolled.

If not, you could try adding a class to the body/html when you open a specific item with 'overflow: hidden' that'd prevent any scrolling.
