### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by grompes** [nolanlawson/pokedex.org#73]
Hi
[RUssia, my english is very bad]
Ребята. А есть такое приложение для Android? Мне понравилась система на сайте, и я уже привык к её подсказкам (например какие атаки сильнее/слабее) и инструкциям (например на каком уровне покемон обучается новым движениям/ударам).
Я не хочу скачивать какие то "рекламные" приложения созданные школьниками-самоучками.
Прошу вас создать версию для android =))

**Comment by nolanlawson** [comment]
Sorry, this is a webapp and there's no intention of creating an Android app. But you can add it to your homescreen and it should function more-or-less like an app.
