### ISSUE TITLE
Broken back link

### ISSUE THREAD

**Issue by royerboat** [nolanlawson/pokedex.org#8]
Noticed this in Safari 9.0.1. Might be related to issue #7 

1. Open up a detail view.
2. Click on the background outside the detail view.
3. Scroll all the way down the page.
4. Click the go back arrow link.
5. Nothing happens and you get the following error in the console:

```TypeError: null is not an object (evaluating 't.parentElement')     main.js:1:9462```

**Comment by nolanlawson** [comment]
Thanks for the bug report! Lots of Safari/iOS stuff to fix. :P

**Comment by connorjburton** [comment]
I have experienced the same issue on Chrome too (Version 49.0.2575.0 canary (64-bit))

**Comment by nolanlawson** [comment]
fixed in #59
